name: CI / CD Pipeline
run-name: ${{ github.actor }} is Deploying 

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Vote service
        uses: docker/build-push-action@v6
        with:
          context: /home/samaneh/voting-app-AWS-EKS-with-CICD/Multi-Stack Voting Application/result 
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/result:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/result:latest

      - name: Build and push Worker service
        uses: docker/build-push-action@v6
        with:
          context: /home/samaneh/voting-app-AWS-EKS-with-CICD/Multi-Stack Voting Application/worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/worker:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/worker:latest

      - name: Build and push Result service
        uses: docker/build-push-action@v6
        with:
          context: /home/samaneh/voting-app-AWS-EKS-with-CICD/Multi-Stack Voting Application/vote
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/vote:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/vote:latest


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin
          mv ./kubectl $HOME/bin/kubectl
          echo "::add-path::$HOME/bin"

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}

      - name: Generate the final deployment template
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base
          export IMAGE_NAME="docker.io/${{ secrets.DOCKER_USERNAME }}/voting-app-vote:${{ env.IMAGE_TAG }}"
          envsubst < k8s/deployment.template.yaml > k8s/deployment.yaml
          echo "Final deployment.yaml:"
          cat k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
